export default [
    {
        id: 2,
        alt: "Myprofile Image",
        Image2: '2.png',
        Greeting: "Hello👋 I’m BYIRINGIRO Aime Fils.",
        aboutMe:"I am passonate in software developemnt especial in MERN Stack</br>Developement (MongoDb,ExpessJs ,ReactJS and Nodejs) and  </br>I completed month working together with Data Stystem(Eshuri Ltd).",
        aboutMe2:"So far, I amcurrently working on different project such as  BabyRead , </br>HB_fashion Store and E-learning platform.Out of coding you'll find</br>me in mixing singers vocal and playing basketball.",
        aboutMe3:"Brielfy I'm Rwandan my residential palce is Rubavu-Gisenyi near to</br> DRC-congo.",
        Name: "Web Designer&Developer.",
        react:'React.png',
        css:'css.png',
        tailwind:'css.png',
        html:'html.png',
        php:'php.png',
        mysqli:'mysqli.png',
        version:'git-alt.svg',
        figma:'figma.png',       
        Node:'Node.png',       
        javascritp:'js.png', 
        Photoshop:'photoshop.png',     
        Illust:'Ai.png',    
      
    },
]